# Atividade Prática 4


Aluno: João Gabriel Angelo Bradachi

Professor: Fabrício Silva

Objetivo: Aplicar técnicas engenharia de atributos no texto da mensagem para gerar atributos relevantes

In [18]:
%pip install nltk optuna

Requirement already satisfied: nltk in /home/bradachi/Documentos/gitpath/ML-engineering-final-project/.venv/lib/python3.12/site-packages (3.10.3)
Collecting optuna
  Downloading optuna-5.0.0-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: defusedxml in /home/bradachi/Documentos/gitpath/ML-engineering-final-project/.venv/lib/python3.12/site-packages (from nltk) (0.7.1)
Requirement already satisfied: click in /home/bradachi/Documentos/gitpath/ML-engineering-final-project/.venv/lib/python3.12/site-packages (from nltk) (8.5.0)
Requirement already satisfied: joblib in /home/bradachi/Documentos/gitpath/ML-engineering-final-project/.venv/lib/python3.12/site-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /home/bradachi/Documentos/gitpath/ML-engineering-final-project/.venv/lib/python3.12/site-packages (from nltk) (2026.9.10)
Requirement already satisfied: tqdm in /home/bradachi/Documentos/gitpath/ML-engineering-final-project/.venv/lib/python3.12/site-packages (from nltk) (4.70.0)
Collecting alembic>=1.5.0 (from optuna)
  Downloading alembic-1.20.0-py3-none-any.whl.metadata (7.3 kB)
Collecting colorlog (from optuna)
  Downloading colorlog-6.12.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy in /home/bradachi/Documentos/gitpath/ML-engineering-final-project/.venv/lib/python3.12/site-packages (from optuna) (2.3.5)
Requirement already satisfied: packaging>=20.0 in /home/bradachi/Documentos/gitpath/ML-engineering-final-project/.venv/lib/python3.12/site-packages (from optuna) (26.3)
Collecting sqlalchemy>=1.4.2 (from optuna)
  Downloading sqlalchemy-2.0.54-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (9.7 kB)
Requirement already satisfied: PyYAML in /home/bradachi/Documentos/gitpath/ML-engineering-final-project/.venv/lib/python3.12/site-packages (from optuna) (6.0.3)
Collecting Mako (from alembic>=1.5.0->optuna)
  Downloading mako-1.4.1-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: typing-extensions>=4.12 in /home/bradachi/Documentos/gitpath/ML-engineering-final-project/.venv/lib/python3.12/site-packages (from alembic>=1.5.0->optuna) (4.16.0)
Collecting greenlet>=1 (from sqlalchemy>=1.4.2->optuna)
  Downloading greenlet-3.5.6-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (3.8 kB)
Requirement already satisfied: MarkupSafe>=2.0 in /home/bradachi/Documentos/gitpath/ML-engineering-final-project/.venv/lib/python3.12/site-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)
Downloading optuna-5.0.0-py3-none-any.whl (442 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 442.4/442.4 kB 2.3 MB/s eta 0:00:0000:0100:01
Downloading alembic-1.20.0-py3-none-any.whl (268 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.7/268.7 kB 1.6 MB/s eta 0:00:00a 0:00:01
Downloading sqlalchemy-2.0.54-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (3.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.5/3.5 MB 2.6 MB/s eta 0:00:0000:0100:01
Downloading colorlog-6.12.0-py3-none-any.whl (12 kB)
Downloading greenlet-3.5.6-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (621 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 621.4/621.4 kB 2.3 MB/s eta 0:00:00a 0:00:01
Downloading mako-1.4.1-py3-none-any.whl (80 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 80.0/80.0 kB 2.9 MB/s eta 0:00:00
Installing collected packages: Mako, greenlet, colorlog, sqlalchemy, alembic, optuna
Successfully installed Mako-1.4.1 alembic-1.20.0 colorlog-6.12.0 greenlet-3.5.6 optuna-5.0.0 sqlalchemy-2.0.54
Note: you may need to restart the kernel to use updated packages.

In [ ]:
# imports
import pandas as pd

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

import optuna
import xgboost as xgb
from sklearn.model_selection import cross_val_score

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import Pipeline
from xgboost import XGBClassifier
from sklearn.metrics import classification_report

/home/bradachi/Documentos/gitpath/ML-engineering-final-project/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [ ]:
# Obtendo dados
df_spam = pd.read_csv("spam-dataset.csv")
df_spam

     Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

## Tratamento dos dados

Para tratar dados textuais, precisamos lidar com a forma que o computador entenda

Vamos realizar 2 tratamentos iniciais: Tokenização e remoção de stop words 

Lematização e Radicalização -> pode ser que piora os dados, se tivermos tempo iremos comparar ao final

## Predição dos dados

Para fazer a predição se é spam ou não, podemos utilizar as seguintes metodologias:

- executar TF-IDF e treinar com o  XGBoost

- Podemos calcular a similaridade de cossenos e ver se o que chegou é mais similar aos que são spam do que com os que não são spam

- usar o Word2Vector para identificar padrões que são parecidos com os spams

In [ ]:
# Tratamento: (Sem Lematização e Radicalização)

stop_words = set(stopwords.words('english'))

# Filtrar as palavras que não estão na lista de stopwords

def remove_sw(texto):
    tokens = word_tokenize(texto.lower())
    filtered_tokens = [word for word in tokens if word not in stop_words]
    clean_text = " ".join(filtered_tokens)
    return clean_text

df_spam['sem_sw'] = df_spam['Message'].apply(remove_sw)
df_spam

,Category,Message,sem_sw
0,ham,"Go until jurong point, crazy.. Available only ...","go jurong point , crazy .. available bugis n g..."
1,ham,Ok lar... Joking wif u oni...,ok lar ... joking wif u oni ...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,free entry 2 wkly comp win fa cup final tkts 2...
3,ham,U dun say so early hor... U c already then say...,u dun say early hor ... u c already say ...
4,ham,"Nah I don't think he goes to usf, he lives aro...","nah n't think goes usf , lives around though"
...,...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...,2nd time tried 2 contact u. u £750 pound prize...
5568,ham,Will ü b going to esplanade fr home?,ü b going esplanade fr home ?
5569,ham,"Pity, * was in mood for that. So...any other s...","pity , * mood . ... suggestions ?"
5570,ham,The guy did some bitching but I acted like i'd...,guy bitching acted like 'd interested buying s...
5571,ham,Rofl. Its true to its name,rofl . true name

In [8]:
# Aplicando TF-IDF

vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(df_spam['sem_sw'])

nomes_recursos = vectorizer.get_feature_names_out()

df_tfidf = pd.DataFrame(tfidf_matrix.toarray(), columns=nomes_recursos)

df_tfidf

,00,000,000pes,008704050406,0089,0121,01223585236,01223585334,0125698789,02,...,zhong,zindgi,zoe,zogtorius,zoom,zouk,zyada,èn,ú1,〨ud
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5567,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5568,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5569,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5570,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5571,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## Testando no XGB 

Aqui nesse ponto nós poderiamos pensar em diminuir as dimensões para deixar o treinamento mais rapido (e talvez melhor)

Vamos treinar com tudo, fazer um fine tunning dos hiper-parametros com cross validation

In [ ]:
# Adicionando o label
df_tfidf['Category'] = df_spam['Category']
df_tfidf

,00,000,000pes,008704050406,0089,0121,01223585236,01223585334,0125698789,02,...,zindgi,zoe,zogtorius,zoom,zouk,zyada,èn,ú1,〨ud,Category
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,ham
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,ham
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,spam
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,ham
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,ham
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5567,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,spam
5568,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,ham
5569,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,ham
5570,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,ham
5571,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,ham

In [21]:
def trata_categoria(categoria):
    if categoria == 'ham': return 0
    elif categoria == 'spam': return 1
    else: return -1

df_tfidf['Category'] = df_tfidf['Category'].apply(trata_categoria)
df_tfidf

,00,000,000pes,008704050406,0089,0121,01223585236,01223585334,0125698789,02,...,zindgi,zoe,zogtorius,zoom,zouk,zyada,èn,ú1,〨ud,Category
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5567,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
5568,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
5569,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
5570,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
5571,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0

In [ ]:
# Treinamento com cross validation

X = df_tfidf.drop('Category', axis=1) 
y = df_tfidf['Category']              

# Definindo a função objetivo para o Optuna
def objective(trial):
  params = {
      'n_estimators': trial.suggest_int('n_estimators', 50, 300),
      'max_depth': trial.suggest_int('max_depth', 3, 9),
      'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3, log=True),
      'subsample': trial.suggest_float('subsample', 0.5, 1.0),
      'colsample_bytree': trial.suggest_float('colsample_bytree', 0.5, 1.0),
      'random_state': 42,
  }

  model = xgb.XGBClassifier(**params)

  # Validação cruzada com 5 folds
  scores = cross_val_score(model, X, y, cv=5, scoring='accuracy', verbose=1)
  return scores.mean()


# Executando o estudo
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=20)

print('Melhores parâmetros:', study.best_params)

[I 2026-09-22 14:12:54,060] A new study created in memory with name: no-name-3074b307-8f6f-432d-b26e-d2e467ea1bd5
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:  7.9min finished
[I 2026-09-22 14:14:45,186] Trial 3 finished with value: 0.9743360893962691 and parameters: {'n_estimators': 180, 'max_depth': 6, 'learning_rate': 0.062198087303159136, 'subsample': 0.9895914421306642, 'colsample_bytree': 0.9972166529015971}. Best is trial 3 with value: 0.9743360893962691.
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:  9.5min finished
[I 2026-09-22 14:16:20,753] Trial 4 finished with value: 0.9599781017784255 and parameters: {'n_estimators': 246, 'max_depth': 5, 'learning_rate': 0.011945801925018722, 'subsample': 0.8261087222002826, 'colsample_bytree': 0.5043480485976634}. Best is trial 3 with value: 0.9743360893962691.
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed: 10.7min finished
[I 2026-09-22 14:17:28,812] Trial 0 finished with value: 0.9775660770785196 and parameters: {'n_estimators': 262, 'max_depth': 9, 'learning_rate': 0.05863729158235281, 'subsample': 0.9196392013785668, 'colsample_bytree': 0.5747126393635869}. Best is trial 0 with value: 0.9775660770785196.
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed: 10.8min finished
[I 2026-09-22 14:17:39,868] Trial 1 finished with value: 0.9745149785445733 and parameters: {'n_estimators': 266, 'max_depth': 9, 'learning_rate': 0.030502403525339433, 'subsample': 0.918278364111899, 'colsample_bytree': 0.7264374302290985}. Best is trial 0 with value: 0.9775660770785196.
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:  5.5min finished
[I 2026-09-22 14:18:21,604] Trial 0 finished with value: 0.9775654330131791 and parameters: {'n_estimators': 163, 'max_depth': 7, 'learning_rate': 0.14678095421929804, 'subsample': 0.7273094543950785, 'colsample_bytree': 0.6688428002149263}. Best is trial 0 with value: 0.9775654330131791.
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:  3.8min finished
[I 2026-09-22 14:22:12,332] Trial 1 finished with value: 0.9781045157031182 and parameters: {'n_estimators': 252, 'max_depth': 7, 'learning_rate': 0.1786794436228906, 'subsample': 0.8581948340323355, 'colsample_bytree': 0.5608402529607184}. Best is trial 1 with value: 0.9781045157031182.
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:  3.5min finished
[I 2026-09-22 14:25:42,920] Trial 2 finished with value: 0.9648245324488169 and parameters: {'n_estimators': 196, 'max_depth': 8, 'learning_rate': 0.01482692376550021, 'subsample': 0.6838061820669883, 'colsample_bytree': 0.6858053725251907}. Best is trial 1 with value: 0.9781045157031182.
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:  2.0min finished
[I 2026-09-22 14:27:43,374] Trial 3 finished with value: 0.953876226743203 and parameters: {'n_estimators': 149, 'max_depth': 3, 'learning_rate': 0.031120839054173628, 'subsample': 0.6810014713628301, 'colsample_bytree': 0.8597492289058155}. Best is trial 1 with value: 0.9781045157031182.
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:  2.5min finished
[I 2026-09-22 14:30:15,867] Trial 4 finished with value: 0.9782834048514222 and parameters: {'n_estimators': 295, 'max_depth': 3, 'learning_rate': 0.1880631789682316, 'subsample': 0.9100883248880922, 'colsample_bytree': 0.676551473173548}. Best is trial 4 with value: 0.9782834048514222.
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:  2.1min finished
[I 2026-09-22 14:32:19,246] Trial 5 finished with value: 0.9748738839555274 and parameters: {'n_estimators': 140, 'max_depth': 8, 'learning_rate': 0.05788815060515789, 'subsample': 0.6181762089239997, 'colsample_bytree': 0.5364154972275343}. Best is trial 4 with value: 0.9782834048514222.
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:  1.6min finished
[I 2026-09-22 14:33:53,869] Trial 6 finished with value: 0.9761301334020335 and parameters: {'n_estimators': 97, 'max_depth': 4, 'learning_rate': 0.2563153343385659, 'subsample': 0.5602468383798835, 'colsample_bytree': 0.6048085291910021}. Best is trial 4 with value: 0.9782834048514222.
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:  2.0min finished
[I 2026-09-22 14:35:51,304] Trial 7 finished with value: 0.9763098276320132 and parameters: {'n_estimators': 122, 'max_depth': 6, 'learning_rate': 0.13407181896902912, 'subsample': 0.8789160406971395, 'colsample_bytree': 0.9023972655393602}. Best is trial 4 with value: 0.9782834048514222.
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:  2.5min finished
[I 2026-09-22 14:38:18,653] Trial 8 finished with value: 0.9755910507120948 and parameters: {'n_estimators': 134, 'max_depth': 5, 'learning_rate': 0.1895481968216076, 'subsample': 0.7470290507324371, 'colsample_bytree': 0.7687771685256275}. Best is trial 4 with value: 0.9782834048514222.
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:  3.8min finished
[I 2026-09-22 14:42:07,973] Trial 9 finished with value: 0.971284990862323 and parameters: {'n_estimators': 207, 'max_depth': 9, 'learning_rate': 0.022874981466270976, 'subsample': 0.7271377863308655, 'colsample_bytree': 0.6567091117529358}. Best is trial 4 with value: 0.9782834048514222.
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:  3.5min finished
[I 2026-09-22 14:45:37,870] Trial 10 finished with value: 0.9725412403088294 and parameters: {'n_estimators': 229, 'max_depth': 5, 'learning_rate': 0.040087248465806115, 'subsample': 0.8500303748388391, 'colsample_bytree': 0.5776646256050156}. Best is trial 4 with value: 0.9782834048514222.
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:  3.5min finished
[I 2026-09-22 14:49:05,275] Trial 11 finished with value: 0.9773857387831996 and parameters: {'n_estimators': 254, 'max_depth': 7, 'learning_rate': 0.16030902350904538, 'subsample': 0.9020471753605709, 'colsample_bytree': 0.6445943645592919}. Best is trial 4 with value: 0.9782834048514222.
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:  3.0min finished
[I 2026-09-22 14:52:04,497] Trial 12 finished with value: 0.9768474611749361 and parameters: {'n_estimators': 278, 'max_depth': 4, 'learning_rate': 0.2012285361979891, 'subsample': 0.762414964906963, 'colsample_bytree': 0.5450245687030406}. Best is trial 4 with value: 0.9782834048514222.
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:  3.8min finished
[I 2026-09-22 14:55:51,152] Trial 13 finished with value: 0.9777449662268237 and parameters: {'n_estimators': 281, 'max_depth': 4, 'learning_rate': 0.19430619402490953, 'subsample': 0.9410214072687791, 'colsample_bytree': 0.7351101989098544}. Best is trial 4 with value: 0.9782834048514222.
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:  4.0min finished
[I 2026-09-22 14:59:53,822] Trial 14 finished with value: 0.9764885557639822 and parameters: {'n_estimators': 280, 'max_depth': 7, 'learning_rate': 0.11425391331825532, 'subsample': 0.8403091010295984, 'colsample_bytree': 0.5123977810044853}. Best is trial 4 with value: 0.9782834048514222.
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:  4.1min finished
[I 2026-09-22 15:04:01,325] Trial 15 finished with value: 0.9766679279612915 and parameters: {'n_estimators': 245, 'max_depth': 9, 'learning_rate': 0.21154830869930596, 'subsample': 0.9918521236123035, 'colsample_bytree': 0.5162130752065134}. Best is trial 4 with value: 0.9782834048514222.
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:  3.0min finished
[I 2026-09-22 15:07:03,482] Trial 16 finished with value: 0.9777451272431588 and parameters: {'n_estimators': 213, 'max_depth': 4, 'learning_rate': 0.2854313597344662, 'subsample': 0.8608357852397702, 'colsample_bytree': 0.7368642490728377}. Best is trial 4 with value: 0.9782834048514222.
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:  2.6min finished
[I 2026-09-22 15:09:39,236] Trial 17 finished with value: 0.9772068496348953 and parameters: {'n_estimators': 194, 'max_depth': 5, 'learning_rate': 0.1389082528094031, 'subsample': 0.9068795170289918, 'colsample_bytree': 0.5248006832208547}. Best is trial 4 with value: 0.9782834048514222.
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:  3.5min finished
[I 2026-09-22 15:13:09,610] Trial 18 finished with value: 0.9755915337611001 and parameters: {'n_estimators': 282, 'max_depth': 4, 'learning_rate': 0.07269037243382875, 'subsample': 0.755595888320331, 'colsample_bytree': 0.5669012496935035}. Best is trial 4 with value: 0.9782834048514222.
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:  3.7min finished
[I 2026-09-22 15:16:52,033] Trial 19 finished with value: 0.9757705839257393 and parameters: {'n_estimators': 271, 'max_depth': 6, 'learning_rate': 0.2510819798731922, 'subsample': 0.8390322576243531, 'colsample_bytree': 0.7729662672516792}. Best is trial 4 with value: 0.9782834048514222.

Melhores parâmetros: {'n_estimators': 295, 'max_depth': 3, 'learning_rate': 0.1880631789682316, 'subsample': 0.9100883248880922, 'colsample_bytree': 0.676551473173548}

## Resultados

In [ ]:
melhores_parametros = {
    'n_estimators': 295,
    'max_depth': 3,
    'learning_rate': 0.1880631789682316,
    'subsample': 0.9100883248880922,
    'colsample_bytree': 0.676551473173548
}

X_treino, X_teste, y_treino, y_teste = train_test_split(X, y, test_size=0.2, random_state=42)

modelo_pipeline = Pipeline(steps=[
    ('classificador', XGBClassifier(
        n_estimators=295,     # Número de árvores
        max_depth=3,          # Profundidade máxima de cada árvore
        learning_rate=0.1880631789682316,
        subsample=0.9100883248880922,
        colsample_bytree=0.676551473173548,
        random_state=42
    ))
])

print("Treinando o modelo...")
modelo_pipeline.fit(X_treino, y_treino)

print("Fazendo previsões no conjunto de teste...")
previsoes = modelo_pipeline.predict(X_teste)

print("\nRelatório de Classificação:")
print(classification_report(y_teste, previsoes, digits=5))

Treinando o modelo...
Fazendo previsões no conjunto de teste...

Relatório de Classificação:
              precision    recall  f1-score   support

           0    0.98067   0.99793   0.98923       966
           1    0.98485   0.87248   0.92527       149

    accuracy                        0.98117      1115
   macro avg    0.98276   0.93521   0.95725      1115
weighted avg    0.98123   0.98117   0.98068      1115

Devido o relatório apresentar bons resultados nas métricas, não irei testar as outras possibilidades.

## Conclusão

Nesse trabalho foi possível observar e colocar em prática como lidar com dados textuais. A prática foi feita com sucesso, gerando um modelo aceitável com poucas ferramentas. Posteriormente testarei as opções ditas e não testadas nesse trabalho a fim de reduzir o custo computacional (reduzir as dimensões dos dados) e obter resultados semelhantes (ou até melhores) dos obtidos